version: "3.8"

services:
  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - "8443:8443"
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME:  ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      
      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: rabbit
      KK_TO_RMQ_PASSWORD: rabbit
      KK_TO_RMQ_USE_TLS: "false"
    depends_on:
      - keycloak_postgres
      - rabbitmq
    networks:
      - keycloak-network
    volumes:
      - ./keycloak-plugin:/opt/keycloak/providers
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command:
      - 'start-dev'

  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - keycloak-network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: keycloak_rabbitmq
    restart: always
    ports:
      - "5672:5672"     # порт для приложений
      - "15672:15672"   # веб-интерфейс RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge

volumes:
  postgres_data:
